// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdk_4QD8Ene30SYxI6U02ZRgJOcg3awZ4',
    appId: '1:601056762695:web:ca2f9213c35d40561e4a62',
    messagingSenderId: '601056762695',
    projectId: 'ctse-event-plan-app',
    authDomain: 'ctse-event-plan-app.firebaseapp.com',
    storageBucket: 'ctse-event-plan-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX5no1ViPi594kdWq-XwHF-jAraWez-BY',
    appId: '1:601056762695:android:b8234facc11c55641e4a62',
    messagingSenderId: '601056762695',
    projectId: 'ctse-event-plan-app',
    storageBucket: 'ctse-event-plan-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArK0z1AzVBsRRmLiRCQaGZFG3WgNrDTDQ',
    appId: '1:601056762695:ios:c32f95d2ed685d0f1e4a62',
    messagingSenderId: '601056762695',
    projectId: 'ctse-event-plan-app',
    storageBucket: 'ctse-event-plan-app.appspot.com',
    iosClientId: '601056762695-df36jp613eu019akmhof6raqtdrcpls2.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventPlanningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArK0z1AzVBsRRmLiRCQaGZFG3WgNrDTDQ',
    appId: '1:601056762695:ios:c32f95d2ed685d0f1e4a62',
    messagingSenderId: '601056762695',
    projectId: 'ctse-event-plan-app',
    storageBucket: 'ctse-event-plan-app.appspot.com',
    iosClientId: '601056762695-df36jp613eu019akmhof6raqtdrcpls2.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventPlanningApp',
  );
}
